server {
    listen 80;
    root /usr/share/nginx/html;

    location /clinicadentalAlamillo/ {
        try_files $uri $uri/ /clinicadentalAlamillo/index.html;
    }

    location = /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}
